name = "level-edge-worker"
main = "src/worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
DATABASE_URL = "libsql://disbot-db-zomka.aws-ap-northeast-1.turso.io"
DISCORD_APPLICATION_ID = "939777923320283176"

# Правила для импорта бинарников
[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = false

[[rules]]
type = "Data"
globs = ["**/*.ttf"]
fallthrough = false